const JENISORDERMUATAN = 1;
const JENISORDERBONGKARAN = 2;
const JENISORDERANIMPORT = 3;
const JENISORDERANEXPORT = 4;

const JENISORDERMUATANNAMA = 'MUATAN';

const STATUSDATAPENDUKUNGYA = 14;
const STATUSDATAPENDUKUNGTIDAK = 15;

export {
  JENISORDERMUATAN,
  JENISORDERBONGKARAN,
  JENISORDERANIMPORT,
  JENISORDERANEXPORT,
  JENISORDERMUATANNAMA,
  STATUSDATAPENDUKUNGTIDAK
};
