import { IMeta } from './error.type';

export interface IShipper {
  id: number;
  statusrelasi: number;
  relasi_id: number;
  nama: string;
  keterangan: string | null;
  contactperson: string | null;
  alamat: string | null;
  coa: number | null;
  coa_text: string | null;
  coapiutang: number | null;
  coapiutang_text: string | null;
  coahutang: number | null;
  coahutang_text: string | null;
  kota: string | null;
  kodepos: string | null;
  telp: string | null;
  email: string | null;
  fax: string | null;
  web: string | null;
  creditlimit: number;
  creditterm: number;
  credittermplus: number | null;
  npwp: string | null;
  coagiro: number | null;
  coagiro_text: string | null;
  ppn: number | null;
  titipke: string | null;
  ppnbatalmuat: number | null;
  grup: string | null;
  formatdeliveryreport: number | null;
  comodity: string | null;
  namashippercetak: string | null;
  formatcetak: number | null;
  marketing_id: number | null;
  marketing_text: string | null;
  blok: string | null;
  nomor: string | null;
  rt: string | null;
  rw: string | null;
  kelurahan: string | null;
  kabupaten: string | null;
  kecamatan: string | null;
  propinsi: string | null;
  isdpp10psn: number | null;
  usertracing: string | null;
  passwordtracing: string | null;
  kodeprospek: string;
  namashipperprospek: string;
  emaildelay: string | null;
  keterangan1barisinvoice: string | null;
  nik: string | null;
  namaparaf: string | null;
  saldopiutang: number | null;
  keteranganshipperjobminus: string | null;
  tglemailshipperjobminus: string | null;
  tgllahir: string;
  idshipperasal: string | null;
  initial: string | null;
  tipe: string | null;
  idtipe: number | null;
  idinitial: number | null;
  nshipperprospek: string | null;
  parentshipper_id: number | null;
  npwpnik: string | null;
  nitku: string | null;
  kodepajak: string | null;
  statusaktif: number;
  text: string | null;
  info: string | null;
  created_at: string;
  updated_at: string;
}

export interface IAllShipper {
  data: IShipper[];
  type: string;
  pagination: IMeta;
}
